/* ======================================================================
 * Title:     nidfdtyp.h                                                 
 *                                                                       
 * Purpose:                                                              
 *            Define the basic datatypes used in the C source files,     
 * which are generated by Digital Filter Design toolkit.                 
 *                                                                       
 * Copyright 2008 National Instruments Corporation. All rights reserved. 
 * ======================================================================
 */

#ifndef __NI_DFD_TYPE_H__
#define __NI_DFD_TYPE_H__

typedef short I16;
typedef long I32;
typedef unsigned long U32;

#endif //#ifndef __NI_DFD_TYPE_H__
